import type {
  Client,
  Production,
  Budget,
  Reminder,
  BudgetTemplate,
} from "./types";

export const INITIAL_CLIENTS: Client[] = [
  {
    id: "cli-001",
    name: "Inmobiliaria Vista Sur",
    type: "inmobiliaria",
    contactName: "Marina Coló",
    contactEmail: "marina.colo@vistasur.com.ar",
    contactPhone: "+54 9 341 555-0142",
    lastContactDate: "2026-08-07",
    logoUrl: "/logos/cli-001.webp",
    notes: [
      {
        id: "note-001",
        date: "2026-08-07",
        text: "Pidió cotizar toma aérea del edificio con luz de atardecer para el lanzamiento comercial.",
      },
      {
        id: "note-002",
        date: "2026-07-29",
        text: "Reunión inicial. Le interesa un paquete de drone + recorrido virtual para 3 desarrollos.",
      },
    ],
  },
  {
    id: "cli-002",
    name: "Constructora Río",
    type: "constructora",
    contactName: "Emiliano Suárez",
    contactEmail: "esuarez@constructorario.com",
    contactPhone: "+54 9 341 555-0198",
    lastContactDate: "2026-08-10",
    logoUrl: "/logos/cli-002.webp",
    notes: [
      {
        id: "note-003",
        date: "2026-08-10",
        text: "Confirmó seguimiento mensual de obra en Torre Norte. Pide entrega los días 28 de cada mes.",
      },
      {
        id: "note-004",
        date: "2026-07-15",
        text: "Primer contacto por recomendación de Inmobiliaria Vista Sur.",
      },
    ],
  },
  {
    id: "cli-003",
    name: "Agencia BTL Norte",
    type: "agencia",
    contactName: "Julieta Fernández",
    contactEmail: "julieta@btlnorte.com.ar",
    contactPhone: "+54 9 11 4555-0177",
    lastContactDate: "2026-08-05",
    logoUrl: "/logos/cli-003.webp",
    notes: [
      {
        id: "note-005",
        date: "2026-08-05",
        text: "Cobertura del evento corporativo de Banco Andes, necesitan entrega de highlights en 48hs.",
      },
    ],
  },
  {
    id: "cli-004",
    name: "Municipalidad de Rosario",
    type: "institucional",
    contactName: "Diego Paz",
    contactEmail: "dpaz@rosario.gob.ar",
    contactPhone: "+54 341 480-2000",
    lastContactDate: "2026-08-03",
    logoUrl: "/logos/cli-004.webp",
    notes: [
      {
        id: "note-006",
        date: "2026-08-03",
        text: "Video institucional de turismo, 2 días de rodaje. Esperando aprobación de presupuesto.",
      },
      {
        id: "note-007",
        date: "2026-07-20",
        text: "Reunión con área de comunicación para definir guion.",
      },
    ],
  },
  {
    id: "cli-005",
    name: "Grupo Eventos Sur",
    type: "eventos",
    contactName: "Lucas Ibáñez",
    contactEmail: "lucas@gruposu.com.ar",
    contactPhone: "+54 9 341 555-0210",
    lastContactDate: "2026-07-31",
    logoUrl: "/logos/cli-005.webp",
    notes: [
      {
        id: "note-008",
        date: "2026-07-31",
        text: "Cerraron cobertura completa de Expo Rosario 2026, 3 jornadas.",
      },
    ],
  },
  {
    id: "cli-006",
    name: "Desarrollos Costanera",
    type: "inmobiliaria",
    contactName: "Rocío Méndez",
    contactEmail: "rmendez@costanera-dev.com",
    contactPhone: "+54 9 341 555-0233",
    lastContactDate: "2026-07-18",
    logoUrl: "/logos/cli-006.webp",
    notes: [
      {
        id: "note-009",
        date: "2026-07-18",
        text: "Presupuesto vencido sin respuesta. Reintentar contacto la próxima semana.",
      },
    ],
  },
  {
    id: "cli-007",
    name: "Inmobiliaria Puerto Norte",
    type: "inmobiliaria",
    contactName: "Sofía Ramírez",
    contactEmail: "sofia.ramirez@puertonorte.com.ar",
    contactPhone: "+54 9 341 555-0251",
    lastContactDate: "2026-08-14",
    notes: [
      {
        id: "note-010",
        date: "2026-08-14",
        text: "Quiere video de drone del nuevo desarrollo en la costanera, con tomas al atardecer.",
      },
    ],
  },
  {
    id: "cli-008",
    name: "Constructora del Paraná",
    type: "constructora",
    contactName: "Martín Ibarra",
    contactEmail: "martin.ibarra@constructoraparana.com.ar",
    contactPhone: "+54 9 341 555-0267",
    lastContactDate: "2026-08-11",
    notes: [
      {
        id: "note-011",
        date: "2026-08-11",
        text: "Pidió presupuesto para seguimiento quincenal de obra en Barrio Fisherton.",
      },
    ],
  },
  {
    id: "cli-009",
    name: "Edificar SRL",
    type: "constructora",
    contactName: "Valentina Roldán",
    contactEmail: "valentina@edificarsrl.com.ar",
    contactPhone: "+54 9 341 555-0289",
    lastContactDate: "2026-08-02",
    notes: [
      {
        id: "note-012",
        date: "2026-08-02",
        text: "Primer contacto, interesados en cobertura del acto de colocación de piedra fundamental.",
      },
    ],
  },
  {
    id: "cli-010",
    name: "Agencia Creativa Litoral",
    type: "agencia",
    contactName: "Nicolás Farías",
    contactEmail: "nico@creativalitoral.com.ar",
    contactPhone: "+54 9 341 555-0304",
    lastContactDate: "2026-08-13",
    notes: [
      {
        id: "note-013",
        date: "2026-08-13",
        text: "Necesitan spot institucional para un cliente propio, entrega en 10 días.",
      },
    ],
  },
  {
    id: "cli-011",
    name: "BTL Sur Producciones",
    type: "agencia",
    contactName: "Camila Duarte",
    contactEmail: "camila.duarte@btlsur.com.ar",
    contactPhone: "+54 9 11 4555-0318",
    lastContactDate: "2026-07-25",
    notes: [
      {
        id: "note-014",
        date: "2026-07-25",
        text: "Activación de marca en shopping, requieren cobertura fotográfica y video corto.",
      },
    ],
  },
  {
    id: "cli-012",
    name: "Municipalidad de Santa Fe",
    type: "institucional",
    contactName: "Tomás Bianchi",
    contactEmail: "tbianchi@santafe.gob.ar",
    contactPhone: "+54 342 457-3000",
    lastContactDate: "2026-08-06",
    notes: [
      {
        id: "note-015",
        date: "2026-08-06",
        text: "Video institucional de obras públicas, licitación en curso.",
      },
    ],
  },
  {
    id: "cli-013",
    name: "Colegio San Martín",
    type: "institucional",
    contactName: "Agustina López",
    contactEmail: "agustina.lopez@colegiosanmartin.edu.ar",
    contactPhone: "+54 341 448-0022",
    lastContactDate: "2026-07-22",
    notes: [
      {
        id: "note-016",
        date: "2026-07-22",
        text: "Cobertura del acto de fin de curso, entrega de diplomas.",
      },
    ],
  },
  {
    id: "cli-014",
    name: "Eventos & Cía",
    type: "eventos",
    contactName: "Franco Suárez",
    contactEmail: "franco@eventosycia.com.ar",
    contactPhone: "+54 9 341 555-0342",
    lastContactDate: "2026-08-16",
    notes: [
      {
        id: "note-017",
        date: "2026-08-16",
        text: "Casamiento corporativo, cobertura completa con dron.",
      },
    ],
  },
  {
    id: "cli-015",
    name: "Producciones Ribera",
    type: "eventos",
    contactName: "Micaela Torres",
    contactEmail: "micaela@produccionesribera.com.ar",
    contactPhone: "+54 9 341 555-0355",
    lastContactDate: "2026-07-29",
    notes: [
      {
        id: "note-018",
        date: "2026-07-29",
        text: "Festival gastronómico en la ribera, 2 días de cobertura.",
      },
    ],
  },
];

export const INITIAL_PRODUCTIONS: Production[] = [
  {
    id: "prod-001",
    clientId: "cli-001",
    title: "Video drone lanzamiento",
    description: "Toma aérea del edificio con luz de atardecer para la campaña de lanzamiento comercial.",
    category: "drone",
    stage: "propuesta",
    startDate: "2026-08-20",
  },
  {
    id: "prod-002",
    clientId: "cli-002",
    title: "Seguimiento mensual de obra, Torre Norte",
    description: "Registro mensual del avance de obra con dron, entrega los días 28 de cada mes.",
    category: "obra",
    stage: "en_produccion",
    startDate: "2026-08-28",
  },
  {
    id: "prod-003",
    clientId: "cli-003",
    title: "Evento corporativo Banco Andes",
    category: "evento",
    stage: "propuesta",
    startDate: "2026-09-02",
  },
  {
    id: "prod-004",
    clientId: "cli-004",
    title: "Video institucional de turismo",
    category: "institucional",
    stage: "propuesta",
    startDate: "2026-09-10",
  },
  {
    id: "prod-005",
    clientId: "cli-005",
    title: "Cobertura Expo Rosario 2026",
    category: "evento",
    stage: "en_produccion",
    startDate: "2026-09-15",
  },
  {
    id: "prod-006",
    clientId: "cli-006",
    title: "Drone + recorrido virtual",
    category: "drone",
    stage: "cancelada",
  },
  {
    id: "prod-007",
    clientId: "cli-007",
    title: "Video drone desarrollo costanera",
    description: "Tomas aéreas del desarrollo en la costanera con luz de atardecer.",
    category: "drone",
    stage: "propuesta",
    startDate: "2026-08-25",
  },
  {
    id: "prod-008",
    clientId: "cli-008",
    title: "Seguimiento quincenal de obra, Barrio Fisherton",
    description: "Registro quincenal del avance de obra con dron.",
    category: "obra",
    stage: "en_produccion",
    startDate: "2026-08-20",
  },
  {
    id: "prod-009",
    clientId: "cli-009",
    title: "Colocación de piedra fundamental",
    description: "Cobertura del acto de colocación de piedra fundamental.",
    category: "institucional",
    stage: "propuesta",
    startDate: "2026-09-05",
  },
  {
    id: "prod-010",
    clientId: "cli-010",
    title: "Spot institucional cliente Agencia Creativa",
    description: "Spot de 30 segundos para un cliente de la agencia.",
    category: "institucional",
    stage: "aprobada",
    startDate: "2026-08-27",
  },
  {
    id: "prod-011",
    clientId: "cli-011",
    title: "Activación de marca en shopping",
    description: "Cobertura fotográfica y video corto de la activación.",
    category: "evento",
    stage: "en_produccion",
    startDate: "2026-08-22",
  },
  {
    id: "prod-012",
    clientId: "cli-012",
    title: "Video institucional obras públicas",
    category: "institucional",
    stage: "propuesta",
    startDate: "2026-09-08",
  },
  {
    id: "prod-013",
    clientId: "cli-013",
    title: "Acto de fin de curso",
    description: "Cobertura del acto de entrega de diplomas.",
    category: "institucional",
    stage: "aprobada",
    startDate: "2026-08-30",
  },
  {
    id: "prod-014",
    clientId: "cli-014",
    title: "Casamiento corporativo",
    description: "Cobertura completa con dron del evento.",
    category: "evento",
    stage: "en_produccion",
    startDate: "2026-08-24",
  },
  {
    id: "prod-015",
    clientId: "cli-015",
    title: "Festival gastronómico en la ribera",
    description: "Cobertura de 2 días del festival.",
    category: "evento",
    stage: "finalizada",
    startDate: "2026-07-30",
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: "PRE-2026-0001",
    clientId: "cli-002",
    productionId: "prod-002",
    title: "Seguimiento mensual de obra, Torre Norte",
    date: "2026-08-01",
    status: "aprobado",
    lineItems: [
      { id: "li-001", description: "Día de rodaje mensual con dron", quantity: 1, unitPrice: 150000 },
      { id: "li-002", description: "Edición y entrega mensual", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "PRE-2026-0002",
    clientId: "cli-004",
    productionId: "prod-004",
    title: "Video institucional 2 días de rodaje + dron + edición",
    date: "2026-08-03",
    status: "visto",
    lineItems: [
      { id: "li-003", description: "Día de rodaje, equipo completo", quantity: 2, unitPrice: 180000 },
      { id: "li-004", description: "Operador de drone + equipo", quantity: 1, unitPrice: 150000 },
      { id: "li-005", description: "Edición y montaje", quantity: 1, unitPrice: 220000 },
      { id: "li-006", description: "Locución profesional", quantity: 1, unitPrice: 60000 },
      { id: "li-007", description: "Motion graphics / titulación", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "PRE-2026-0003",
    clientId: "cli-003",
    productionId: "prod-003",
    title: "Cobertura audiovisual, Evento Banco Andes",
    date: "2026-08-05",
    status: "enviado",
    emailSentAt: "2026-08-05T14:30:00.000Z",
    lineItems: [
      { id: "li-008", description: "Cobertura fotográfica del evento", quantity: 1, unitPrice: 110000 },
      { id: "li-009", description: "Cobertura de video + highlights 48hs", quantity: 1, unitPrice: 160000 },
      { id: "li-010", description: "Edición de reel para redes", quantity: 1, unitPrice: 70000 },
    ],
  },
  {
    id: "PRE-2026-0004",
    clientId: "cli-006",
    productionId: "prod-006",
    title: "Drone + recorrido virtual",
    date: "2026-07-10",
    status: "vencido",
    lineItems: [
      { id: "li-011", description: "Día de rodaje con dron", quantity: 1, unitPrice: 150000 },
      { id: "li-012", description: "Recorrido virtual 360°", quantity: 1, unitPrice: 130000 },
    ],
  },
  {
    id: "PRE-2026-0005",
    clientId: "cli-001",
    productionId: "prod-001",
    title: "Video drone lanzamiento",
    date: "2026-08-12",
    status: "en_espera",
    lineItems: [
      { id: "li-013", description: "Día de rodaje con dron", quantity: 1, unitPrice: 150000 },
      { id: "li-014", description: "Edición y montaje", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "PRE-2026-0006",
    clientId: "cli-005",
    productionId: "prod-005",
    title: "Cobertura Expo Rosario 2026",
    date: "2026-08-15",
    status: "aprobado",
    lineItems: [
      { id: "li-015", description: "Cobertura fotográfica y de video, 3 jornadas", quantity: 3, unitPrice: 140000 },
      { id: "li-016", description: "Edición de reel para redes", quantity: 1, unitPrice: 80000 },
    ],
  },
  {
    id: "PRE-2026-0007",
    clientId: "cli-007",
    productionId: "prod-007",
    title: "Video drone desarrollo costanera",
    date: "2026-08-16",
    status: "en_espera",
    lineItems: [
      { id: "li-017", description: "Día de rodaje con dron", quantity: 1, unitPrice: 150000 },
      { id: "li-018", description: "Edición y montaje", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "PRE-2026-0008",
    clientId: "cli-008",
    productionId: "prod-008",
    title: "Seguimiento quincenal de obra, Barrio Fisherton",
    date: "2026-08-12",
    status: "enviado",
    emailSentAt: "2026-08-12T10:15:00.000Z",
    lineItems: [
      { id: "li-019", description: "Día de rodaje quincenal con dron", quantity: 1, unitPrice: 140000 },
      { id: "li-020", description: "Edición y entrega quincenal", quantity: 1, unitPrice: 85000 },
    ],
  },
  {
    id: "PRE-2026-0009",
    clientId: "cli-009",
    productionId: "prod-009",
    title: "Colocación de piedra fundamental",
    date: "2026-08-04",
    status: "visto",
    lineItems: [
      { id: "li-021", description: "Cobertura fotográfica del acto", quantity: 1, unitPrice: 90000 },
      { id: "li-022", description: "Cobertura de video", quantity: 1, unitPrice: 120000 },
    ],
  },
  {
    id: "PRE-2026-0010",
    clientId: "cli-010",
    productionId: "prod-010",
    title: "Spot institucional cliente Agencia Creativa",
    date: "2026-08-14",
    status: "aprobado",
    lineItems: [
      { id: "li-023", description: "Día de rodaje, equipo completo", quantity: 1, unitPrice: 180000 },
      { id: "li-024", description: "Edición y montaje", quantity: 1, unitPrice: 200000 },
      { id: "li-025", description: "Motion graphics / titulación", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "PRE-2026-0011",
    clientId: "cli-011",
    productionId: "prod-011",
    title: "Activación de marca en shopping",
    date: "2026-07-20",
    status: "vencido",
    lineItems: [
      { id: "li-026", description: "Cobertura fotográfica", quantity: 1, unitPrice: 100000 },
      { id: "li-027", description: "Video corto para redes", quantity: 1, unitPrice: 130000 },
    ],
  },
  {
    id: "PRE-2026-0012",
    clientId: "cli-012",
    productionId: "prod-012",
    title: "Video institucional obras públicas",
    date: "2026-08-09",
    status: "en_espera",
    lineItems: [
      { id: "li-028", description: "Día de rodaje, equipo completo", quantity: 2, unitPrice: 180000 },
      { id: "li-029", description: "Edición y montaje", quantity: 1, unitPrice: 220000 },
    ],
  },
  {
    id: "PRE-2026-0013",
    clientId: "cli-013",
    productionId: "prod-013",
    title: "Acto de fin de curso",
    date: "2026-08-17",
    status: "enviado",
    emailSentAt: "2026-08-17T09:00:00.000Z",
    lineItems: [
      { id: "li-030", description: "Cobertura fotográfica", quantity: 1, unitPrice: 90000 },
      { id: "li-031", description: "Cobertura de video", quantity: 1, unitPrice: 110000 },
    ],
  },
  {
    id: "PRE-2026-0014",
    clientId: "cli-014",
    productionId: "prod-014",
    title: "Casamiento corporativo",
    date: "2026-08-15",
    status: "visto",
    lineItems: [
      { id: "li-032", description: "Cobertura fotográfica y de video, día completo", quantity: 1, unitPrice: 220000 },
      { id: "li-033", description: "Operador de drone", quantity: 1, unitPrice: 150000 },
      { id: "li-034", description: "Edición y montaje", quantity: 1, unitPrice: 180000 },
    ],
  },
  {
    id: "PRE-2026-0015",
    clientId: "cli-015",
    productionId: "prod-015",
    title: "Festival gastronómico en la ribera",
    date: "2026-07-25",
    status: "aprobado",
    lineItems: [
      { id: "li-035", description: "Cobertura fotográfica y de video, 2 jornadas", quantity: 2, unitPrice: 140000 },
      { id: "li-036", description: "Edición de reel para redes", quantity: 1, unitPrice: 80000 },
    ],
  },
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: "rem-001",
    clientId: "cli-002",
    text: "Llamar a Constructora Río",
    dueDate: "2026-08-11",
    done: false,
  },
  {
    id: "rem-002",
    clientId: "cli-001",
    text: "Enviar propuesta actualizada de video drone",
    dueDate: "2026-08-12",
    done: false,
  },
  {
    id: "rem-003",
    clientId: "cli-003",
    text: "Confirmar fecha de rodaje, evento Banco Andes",
    dueDate: "2026-08-13",
    done: false,
  },
  {
    id: "rem-004",
    clientId: "cli-004",
    text: "Seguimiento de presupuesto institucional",
    dueDate: "2026-08-09",
    done: true,
  },
  {
    id: "rem-005",
    clientId: "cli-005",
    text: "Confirmar pago final Expo Rosario 2026",
    dueDate: "2026-08-18",
    done: false,
  },
  {
    id: "rem-006",
    clientId: "cli-006",
    text: "Reintentar contacto, presupuesto vencido",
    dueDate: "2026-08-20",
    done: false,
  },
  {
    id: "rem-007",
    clientId: "cli-007",
    text: "Enviar propuesta video drone costanera",
    dueDate: "2026-08-19",
    done: false,
  },
  {
    id: "rem-008",
    clientId: "cli-008",
    text: "Coordinar próxima fecha de rodaje quincenal",
    dueDate: "2026-08-22",
    done: false,
  },
  {
    id: "rem-009",
    clientId: "cli-009",
    text: "Confirmar fecha de colocación de piedra fundamental",
    dueDate: "2026-08-25",
    done: false,
  },
  {
    id: "rem-010",
    clientId: "cli-010",
    text: "Revisar guion spot institucional",
    dueDate: "2026-08-21",
    done: true,
  },
  {
    id: "rem-011",
    clientId: "cli-011",
    text: "Enviar fotos de la activación en el shopping",
    dueDate: "2026-08-14",
    done: true,
  },
  {
    id: "rem-012",
    clientId: "cli-012",
    text: "Seguimiento de licitación municipal",
    dueDate: "2026-08-28",
    done: false,
  },
  {
    id: "rem-013",
    clientId: "cli-013",
    text: "Coordinar horario del acto de fin de curso",
    dueDate: "2026-08-29",
    done: false,
  },
  {
    id: "rem-014",
    clientId: "cli-014",
    text: "Confirmar itinerario del casamiento corporativo",
    dueDate: "2026-08-23",
    done: false,
  },
  {
    id: "rem-015",
    clientId: "cli-015",
    text: "Enviar reel del festival gastronómico",
    dueDate: "2026-08-01",
    done: true,
  },
];

export const INITIAL_BUDGET_TEMPLATES: BudgetTemplate[] = [
  {
    id: "tpl-001",
    name: "Video institucional 2 días + dron + edición",
    lineItems: [
      { description: "Día de rodaje, equipo completo", quantity: 2, unitPrice: 180000 },
      { description: "Operador de drone + equipo", quantity: 1, unitPrice: 150000 },
      { description: "Edición y montaje", quantity: 1, unitPrice: 220000 },
      { description: "Locución profesional", quantity: 1, unitPrice: 60000 },
      { description: "Motion graphics / titulación", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "tpl-002",
    name: "Seguimiento mensual de obra",
    lineItems: [
      { description: "Día de rodaje mensual con dron", quantity: 1, unitPrice: 150000 },
      { description: "Edición y entrega mensual", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "tpl-003",
    name: "Cobertura de evento corporativo",
    lineItems: [
      { description: "Cobertura fotográfica del evento", quantity: 1, unitPrice: 110000 },
      { description: "Cobertura de video + highlights 48hs", quantity: 1, unitPrice: 160000 },
      { description: "Edición de reel para redes", quantity: 1, unitPrice: 70000 },
    ],
  },
  {
    id: "tpl-004",
    name: "Cobertura de casamiento corporativo",
    lineItems: [
      { description: "Cobertura fotográfica y de video, día completo", quantity: 1, unitPrice: 220000 },
      { description: "Operador de drone", quantity: 1, unitPrice: 150000 },
      { description: "Edición y montaje", quantity: 1, unitPrice: 180000 },
    ],
  },
  {
    id: "tpl-005",
    name: "Activación de marca / shopping",
    lineItems: [
      { description: "Cobertura fotográfica", quantity: 1, unitPrice: 100000 },
      { description: "Video corto para redes", quantity: 1, unitPrice: 130000 },
    ],
  },
  {
    id: "tpl-006",
    name: "Spot institucional 30 segundos",
    lineItems: [
      { description: "Día de rodaje, equipo completo", quantity: 1, unitPrice: 180000 },
      { description: "Edición y montaje", quantity: 1, unitPrice: 200000 },
      { description: "Motion graphics / titulación", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "tpl-007",
    name: "Acto institucional / entrega de diplomas",
    lineItems: [
      { description: "Cobertura fotográfica", quantity: 1, unitPrice: 90000 },
      { description: "Cobertura de video", quantity: 1, unitPrice: 110000 },
    ],
  },
  {
    id: "tpl-008",
    name: "Colocación de piedra fundamental",
    lineItems: [
      { description: "Cobertura fotográfica del acto", quantity: 1, unitPrice: 90000 },
      { description: "Cobertura de video", quantity: 1, unitPrice: 120000 },
    ],
  },
  {
    id: "tpl-009",
    name: "Video institucional de obra pública",
    lineItems: [
      { description: "Día de rodaje, equipo completo", quantity: 2, unitPrice: 180000 },
      { description: "Edición y montaje", quantity: 1, unitPrice: 220000 },
    ],
  },
  {
    id: "tpl-010",
    name: "Festival / evento de 2 días",
    lineItems: [
      { description: "Cobertura fotográfica y de video, 2 jornadas", quantity: 2, unitPrice: 140000 },
      { description: "Edición de reel para redes", quantity: 1, unitPrice: 80000 },
    ],
  },
  {
    id: "tpl-011",
    name: "Recorrido virtual 360°",
    lineItems: [
      { description: "Día de rodaje con dron", quantity: 1, unitPrice: 150000 },
      { description: "Recorrido virtual 360°", quantity: 1, unitPrice: 130000 },
    ],
  },
  {
    id: "tpl-012",
    name: "Seguimiento quincenal de obra",
    lineItems: [
      { description: "Día de rodaje quincenal con dron", quantity: 1, unitPrice: 140000 },
      { description: "Edición y entrega quincenal", quantity: 1, unitPrice: 85000 },
    ],
  },
  {
    id: "tpl-013",
    name: "Video de lanzamiento comercial",
    lineItems: [
      { description: "Día de rodaje con dron", quantity: 1, unitPrice: 150000 },
      { description: "Edición y montaje", quantity: 1, unitPrice: 90000 },
    ],
  },
  {
    id: "tpl-014",
    name: "Cobertura fotográfica simple",
    lineItems: [{ description: "Cobertura fotográfica, medio día", quantity: 1, unitPrice: 70000 }],
  },
  {
    id: "tpl-015",
    name: "Paquete institucional completo",
    lineItems: [
      { description: "Día de rodaje, equipo completo", quantity: 1, unitPrice: 180000 },
      { description: "Operador de drone", quantity: 1, unitPrice: 150000 },
      { description: "Edición y montaje", quantity: 1, unitPrice: 220000 },
      { description: "Locución profesional", quantity: 1, unitPrice: 60000 },
      { description: "Motion graphics / titulación", quantity: 1, unitPrice: 90000 },
      { description: "Recorrido virtual 360°", quantity: 1, unitPrice: 130000 },
    ],
  },
];

let budgetNumberSeq = INITIAL_BUDGETS.length + 1;

export function nextBudgetId(): string {
  const year = new Date().getFullYear();
  const id = `PRE-${year}-${String(budgetNumberSeq).padStart(4, "0")}`;
  budgetNumberSeq += 1;
  return id;
}
